name: Verify Recipe Format

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Verify Recipe Format
      run: python scripts/format-check.py
